name: Run noVNC in GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install qemu-kvm qemu-system-x86 openbox firefox tigervnc-standalone-server
        git clone https://github.com/novnc/noVNC
        

    - name: Start VNC server
      run: |
        sudo vncserver -SecurityType none -xstartup "openbox" -rfbport 5900
        sudo ./utils/novnc_proxy --vnc 127.0.0.1:5900 --listen localhost:6080
